import type {
  AgentRun,
  AttentionItem,
  CausalEdge,
  CausalNode,
  Change,
  Evidence,
  IncidentSummary,
  MetricSeries,
  PulseMetric,
  ReportMetrics,
  Service,
  TimelineEvent,
} from "@/types/threadline";

/** A frozen clock keeps screenshots, relative times, and tests reproducible. */
export const DEMO_NOW = "2026-07-14T10:42:00.000Z";

export const incidentSummary: IncidentSummary = {
  id: "INC-2471",
  title: "Checkout latency elevated",
  severity: "SEV-2",
  status: "resolved",
  startedAt: "2026-07-14T09:24:00.000Z",
  resolvedAt: "2026-07-14T09:40:00.000Z",
  commander: "Maya Chen",
  serviceIds: ["checkout-api", "tax-adapter", "web-storefront"],
  customerImpact:
    "Checkout conversion fell 7.3% relative while latency was elevated, with an estimated revenue impact of $12.4k per hour.",
  rootCause:
    "PR #1842 raised outbound tax quote retries from one to three; at 100% instant-tax-v2 exposure, retry amplification saturated the tax-adapter connection pool.",
};

export const services: readonly Service[] = [
  {
    id: "web-storefront",
    name: "Web storefront",
    slug: "web-storefront",
    kind: "frontend",
    owner: "Shopping Experience",
    description: "Customer-facing Next.js storefront and checkout entry point.",
    runtime: "Next.js 16 · Edge",
    repository: "meridian/web-storefront",
    health: "healthy",
    version: "2026.07.14.3",
    slo: { availability: 99.95, latencyP95Ms: 900, windowDays: 30 },
    tags: ["tier:1", "surface:web", "region:global"],
    dependencyIds: ["edge-gateway"],
    position: { x: 68, y: 220 },
  },
  {
    id: "edge-gateway",
    name: "Edge gateway",
    slug: "edge-gateway",
    kind: "gateway",
    owner: "Core Platform",
    description: "Authenticates and routes public commerce API traffic.",
    runtime: "Go 1.24 · Kubernetes",
    repository: "meridian/edge-gateway",
    health: "healthy",
    version: "v2.44.1",
    slo: { availability: 99.99, latencyP95Ms: 180, windowDays: 30 },
    tags: ["tier:0", "protocol:http", "region:multi"],
    dependencyIds: ["identity", "cart", "checkout-api"],
    position: { x: 268, y: 220 },
  },
  {
    id: "identity",
    name: "Identity",
    slug: "identity",
    kind: "service",
    owner: "Trust Platform",
    description: "Session validation, customer identity, and risk claims.",
    runtime: "Kotlin 2.2 · JVM",
    repository: "meridian/identity",
    health: "healthy",
    version: "v5.9.2",
    slo: { availability: 99.99, latencyP95Ms: 120, windowDays: 30 },
    tags: ["tier:0", "data:pii", "region:multi"],
    dependencyIds: [],
    position: { x: 468, y: 48 },
  },
  {
    id: "tax-adapter",
    name: "Tax adapter",
    slug: "tax-adapter",
    kind: "service",
    owner: "Commerce Core",
    description: "Normalizes outbound tax quote requests and manages provider connection pools.",
    runtime: "Go 1.24 · Kubernetes",
    repository: "meridian/tax-adapter",
    health: "degraded",
    version: "v4.8.2",
    slo: { availability: 99.95, latencyP95Ms: 450, windowDays: 30 },
    tags: ["tier:0", "domain:tax", "protocol:http"],
    dependencyIds: [],
    position: { x: 468, y: 152 },
  },
  {
    id: "cart",
    name: "Cart",
    slug: "cart",
    kind: "service",
    owner: "Shopping Experience",
    description: "Persistent basket, promotions, and price reconciliation.",
    runtime: "TypeScript · Node.js 24",
    repository: "meridian/cart",
    health: "healthy",
    version: "v4.27.3",
    slo: { availability: 99.95, latencyP95Ms: 320, windowDays: 30 },
    tags: ["tier:1", "domain:commerce", "cache:redis"],
    dependencyIds: ["inventory"],
    position: { x: 468, y: 256 },
  },
  {
    id: "checkout-api",
    name: "Checkout API",
    slug: "checkout-api",
    kind: "service",
    owner: "Checkout Reliability",
    description: "Orchestrates totals, tax quotes, inventory reservation, and payment authorization.",
    runtime: "Go 1.24 · Kubernetes",
    repository: "meridian/checkout-api",
    health: "critical",
    version: "2.18.0",
    slo: { availability: 99.95, latencyP95Ms: 800, windowDays: 30 },
    tags: ["tier:0", "domain:commerce", "oncall:checkout"],
    dependencyIds: ["cart", "payments", "inventory", "tax-adapter"],
    position: { x: 468, y: 360 },
  },
  {
    id: "payments",
    name: "Payments",
    slug: "payments",
    kind: "service",
    owner: "Money Movement",
    description: "Payment tokenization, authorization, and settlement adapter.",
    runtime: "Java 24 · Kubernetes",
    repository: "meridian/payments",
    health: "healthy",
    version: "v7.12.4",
    slo: { availability: 99.99, latencyP95Ms: 650, windowDays: 30 },
    tags: ["tier:0", "compliance:pci", "region:multi"],
    dependencyIds: [],
    position: { x: 684, y: 314 },
  },
  {
    id: "inventory",
    name: "Inventory",
    slug: "inventory",
    kind: "service",
    owner: "Fulfillment Platform",
    description: "Available-to-promise reads and short-lived stock reservations.",
    runtime: "Rust 1.88 · Kubernetes",
    repository: "meridian/inventory",
    health: "healthy",
    version: "v6.4.8",
    slo: { availability: 99.95, latencyP95Ms: 260, windowDays: 30 },
    tags: ["tier:1", "domain:fulfillment", "protocol:grpc"],
    dependencyIds: [],
    position: { x: 684, y: 208 },
  },
];

export const evidence: readonly Evidence[] = [
  {
    id: "ev-pr-1842",
    kind: "pull-request",
    title: "PR #1842 · Retry outbound tax quote requests",
    source: "GitHub",
    timestamp: "2026-07-14T09:08:00.000Z",
    summary: "The diff raises outbound tax quote retries from one to three for the instant-tax-v2 path.",
    serviceIds: ["checkout-api", "tax-adapter"],
    externalUrl: "https://github.com/meridian/checkout-api/pull/1842",
    attributes: { commit: "9f3c2ad", files: 4, additions: 42, deletions: 18, retriesBefore: 1, retriesAfter: 3 },
  },
  {
    id: "ev-deploy-2180",
    kind: "deployment",
    title: "checkout-api@2.18.0 production deployment",
    source: "Vercel Deployments",
    timestamp: "2026-07-14T09:12:00.000Z",
    summary: "All six production instances reported checkout-api@2.18.0 after rollout checks passed.",
    serviceIds: ["checkout-api"],
    externalUrl: "https://vercel.com/meridian/checkout-api/deployments/dep_2180",
    attributes: { version: "2.18.0", environment: "production", instances: 6 },
  },
  {
    id: "ev-flag-instant-tax-v2",
    kind: "log",
    title: "instant-tax-v2 exposure increased from 50% to 100%",
    source: "Feature flag audit",
    timestamp: "2026-07-14T09:18:00.000Z",
    summary: "Production exposure doubled six minutes after checkout-api@2.18.0 reached all instances.",
    serviceIds: ["checkout-api", "tax-adapter"],
    externalUrl: "https://flags.meridian.example/audit/instant-tax-v2",
    attributes: { flag: "instant-tax-v2", beforePercent: 50, afterPercent: 100, environment: "production" },
  },
  {
    id: "ev-trace-tax-7f91",
    kind: "trace",
    title: "Trace 7f91 · tax-adapter pool acquisition on POST /checkout",
    source: "OpenTelemetry",
    timestamp: "2026-07-14T09:21:20.000Z",
    summary: "Ninety-two percent of slow checkout traces wait on tax-adapter connection acquisition after retry fan-out.",
    serviceIds: ["checkout-api", "tax-adapter"],
    externalUrl: "https://traces.meridian.example/trace/7f91a821",
    attributes: { durationMs: 1840, spans: 34, poolWaitPercent: 92, outboundAttempts: 3 },
  },
  {
    id: "ev-metric-checkout",
    kind: "metric",
    title: "Checkout p95 reached 1.84 s and errors reached 4.9%",
    source: "SLO monitor",
    timestamp: "2026-07-14T09:22:00.000Z",
    summary: "Latency rose from a 680 ms baseline while short-window SLO burn reached 8.4×; traffic stayed within 2% of baseline.",
    serviceIds: ["checkout-api", "tax-adapter"],
    externalUrl: "https://app.datadoghq.com/dashboard/meridian-checkout-slo",
    attributes: { baselineMs: 680, observedMs: 1840, errorRatePercent: 4.9, burnRate: 8.4, trafficDeltaPercent: 1.8 },
  },
  {
    id: "ev-commerce-conversion",
    kind: "metric",
    title: "Checkout conversion fell 7.3% relative",
    source: "Meridian Commerce",
    timestamp: "2026-07-14T09:23:00.000Z",
    summary: "The conversion decline aligns with the elevated-latency window and models $12.4k in hourly revenue impact.",
    serviceIds: ["web-storefront", "checkout-api"],
    externalUrl: "https://commerce.meridian.example/analytics/checkout-conversion",
    attributes: { baselinePercent: 68.4, observedPercent: 63.5, relativeChangePercent: -7.3, revenueImpactPerHourUsd: -12400 },
  },
  {
    id: "ev-runbook-instant-tax-v2",
    kind: "runbook",
    title: "Runbook · Disable instant-tax-v2 safely",
    source: "Linear",
    timestamp: "2026-07-14T09:25:00.000Z",
    summary: "The runbook requires a Production Operator to disable the flag and verify checkout p95 for five minutes.",
    serviceIds: ["checkout-api", "tax-adapter"],
    externalUrl: "https://linear.app/meridian/document/instant-tax-v2-mitigation",
    attributes: { owner: "Commerce Core", revision: 12, verificationMinutes: 5, requiredRole: "Production Operator" },
  },
];

export const changes: readonly Change[] = [
  {
    id: "chg-1842",
    title: "Retry outbound tax quote requests",
    kind: "configuration",
    status: "deployed",
    repository: "meridian/checkout-api",
    branch: "maya/tax-quote-retries",
    commitSha: "9f3c2ad",
    pullRequest: 1842,
    author: "Maya Chen",
    mergedAt: "2026-07-14T09:08:00.000Z",
    deployedAt: "2026-07-14T09:12:00.000Z",
    serviceIds: ["checkout-api", "tax-adapter"],
    linesAdded: 42,
    linesDeleted: 18,
    filesChanged: 4,
    risk: { score: 92, level: "critical", factors: ["Tier-0 path", "Retry amplification", "100% feature-flag exposure"] },
    evidenceIds: ["ev-pr-1842", "ev-deploy-2180", "ev-flag-instant-tax-v2", "ev-trace-tax-7f91", "ev-metric-checkout"],
  },
  {
    id: "chg-839",
    title: "Show promotion savings in cart summary",
    kind: "feature",
    status: "deployed",
    repository: "meridian/cart",
    branch: "mira/promo-summary",
    commitSha: "3a9e71c",
    pullRequest: 839,
    author: "Mira Shah",
    mergedAt: "2026-07-14T05:18:00.000Z",
    deployedAt: "2026-07-14T06:02:00.000Z",
    serviceIds: ["cart", "web-storefront"],
    linesAdded: 242,
    linesDeleted: 41,
    filesChanged: 12,
    risk: { score: 46, level: "medium", factors: ["Cross-service contract", "Customer-facing copy"] },
    evidenceIds: [],
  },
  {
    id: "chg-836",
    title: "Add inventory reservation span attributes",
    kind: "observability",
    status: "deployed",
    repository: "meridian/inventory",
    branch: "leo/reservation-otel-attrs",
    commitSha: "b74a681",
    pullRequest: 836,
    author: "Leo Martins",
    mergedAt: "2026-07-13T22:44:00.000Z",
    deployedAt: "2026-07-14T00:12:00.000Z",
    serviceIds: ["inventory"],
    linesAdded: 67,
    linesDeleted: 12,
    filesChanged: 4,
    risk: { score: 18, level: "low", factors: ["Telemetry-only change"] },
    evidenceIds: [],
  },
  {
    id: "chg-835",
    title: "Upgrade payment token SDK to 6.4.2",
    kind: "dependency",
    status: "ready",
    repository: "meridian/payments",
    branch: "renovate/payment-token-6.x",
    commitSha: "de82f0a",
    pullRequest: 835,
    author: "Renovate Bot",
    mergedAt: "2026-07-14T09:54:00.000Z",
    deployedAt: null,
    serviceIds: ["payments"],
    linesAdded: 14,
    linesDeleted: 14,
    filesChanged: 3,
    risk: { score: 58, level: "medium", factors: ["PCI boundary", "Third-party dependency"] },
    evidenceIds: [],
  },
  {
    id: "chg-829",
    title: "Cap reservation retry backoff at two seconds",
    kind: "fix",
    status: "rolling-out",
    repository: "meridian/inventory",
    branch: "sofia/retry-cap",
    commitSha: "6718ac4",
    pullRequest: 829,
    author: "Sofia Rossi",
    mergedAt: "2026-07-14T08:58:00.000Z",
    deployedAt: "2026-07-14T10:31:00.000Z",
    serviceIds: ["inventory", "checkout-api"],
    linesAdded: 91,
    linesDeleted: 38,
    filesChanged: 6,
    risk: { score: 64, level: "high", factors: ["Retry behavior", "Checkout dependency", "Active canary"] },
    evidenceIds: [],
  },
  {
    id: "chg-826",
    title: "Rotate session signing key without restart",
    kind: "refactor",
    status: "blocked",
    repository: "meridian/identity",
    branch: "nora/hot-key-rotation",
    commitSha: "1d605fc",
    pullRequest: 826,
    author: "Nora Kim",
    mergedAt: "2026-07-14T04:10:00.000Z",
    deployedAt: null,
    serviceIds: ["identity", "edge-gateway"],
    linesAdded: 318,
    linesDeleted: 126,
    filesChanged: 18,
    risk: { score: 78, level: "high", factors: ["Authentication path", "Cryptographic material", "Large diff"] },
    evidenceIds: [],
  },
];

export const causalNodes: readonly CausalNode[] = [
  {
    id: "node-change-1842",
    kind: "change",
    title: "PR #1842 merged",
    subtitle: "Tax quote retries raised from 1 to 3",
    timestamp: "2026-07-14T09:08:00.000Z",
    severity: "high",
    serviceId: "checkout-api",
    evidenceIds: ["ev-pr-1842"],
    position: { x: 36, y: 92 },
    metadata: { changeId: "chg-1842", riskScore: 92, retriesBefore: 1, retriesAfter: 3 },
  },
  {
    id: "node-deploy-2180",
    kind: "deployment",
    title: "checkout-api@2.18.0 deployed",
    subtitle: "All six production instances ready",
    timestamp: "2026-07-14T09:12:00.000Z",
    severity: "medium",
    serviceId: "checkout-api",
    evidenceIds: ["ev-deploy-2180"],
    position: { x: 210, y: 92 },
    metadata: { version: "2.18.0", environment: "production", instances: 6 },
  },
  {
    id: "node-flag-rollout",
    kind: "change",
    title: "instant-tax-v2 set to 100%",
    subtitle: "Production exposure doubled from 50%",
    timestamp: "2026-07-14T09:18:00.000Z",
    severity: "high",
    serviceId: "checkout-api",
    evidenceIds: ["ev-flag-instant-tax-v2"],
    position: { x: 386, y: 36 },
    metadata: { flag: "instant-tax-v2", beforePercent: 50, afterPercent: 100 },
  },
  {
    id: "node-checkout",
    kind: "service",
    title: "Checkout API",
    subtitle: "Outbound tax quote retry amplification",
    timestamp: "2026-07-14T09:19:00.000Z",
    severity: "critical",
    serviceId: "checkout-api",
    evidenceIds: ["ev-flag-instant-tax-v2", "ev-trace-tax-7f91", "ev-metric-checkout"],
    position: { x: 386, y: 154 },
    metadata: { owner: "Commerce Core", version: "2.18.0", outboundRetries: 3 },
  },
  {
    id: "node-latency",
    kind: "metric",
    title: "p95 latency breached",
    subtitle: "680 ms → 1.84 s",
    timestamp: "2026-07-14T09:21:30.000Z",
    severity: "critical",
    serviceId: "checkout-api",
    evidenceIds: ["ev-trace-tax-7f91", "ev-metric-checkout"],
    position: { x: 558, y: 82 },
    metadata: { baselineMs: 680, observedMs: 1840, thresholdMs: 800 },
  },
  {
    id: "node-alert",
    kind: "alert",
    title: "Checkout SLO burn alert",
    subtitle: "8.4× burn rate",
    timestamp: "2026-07-14T09:22:00.000Z",
    severity: "critical",
    serviceId: "checkout-api",
    evidenceIds: ["ev-metric-checkout"],
    position: { x: 730, y: 36 },
    metadata: { burnRate: 8.4, monitor: "checkout-latency-slo" },
  },
  {
    id: "node-trace",
    kind: "trace",
    title: "Trace 7f91 isolated pool saturation",
    subtitle: "92% of slow traces wait on tax-adapter",
    timestamp: "2026-07-14T09:21:20.000Z",
    severity: "high",
    serviceId: "tax-adapter",
    evidenceIds: ["ev-trace-tax-7f91"],
    position: { x: 558, y: 202 },
    metadata: { traceId: "7f91a821", durationMs: 1840, poolWaitPercent: 92 },
  },
  {
    id: "node-error-rate",
    kind: "metric",
    title: "Checkout errors increased",
    subtitle: "0.7% → 4.9%",
    timestamp: "2026-07-14T09:22:00.000Z",
    severity: "high",
    serviceId: "checkout-api",
    evidenceIds: ["ev-trace-tax-7f91", "ev-metric-checkout"],
    position: { x: 730, y: 202 },
    metadata: { baselinePercent: 0.7, observedPercent: 4.9 },
  },
  {
    id: "node-impact",
    kind: "customer-impact",
    title: "Checkout conversion declined",
    subtitle: "−7.3% relative · −$12.4k/hour",
    timestamp: "2026-07-14T09:23:00.000Z",
    severity: "critical",
    serviceId: "web-storefront",
    evidenceIds: ["ev-metric-checkout", "ev-commerce-conversion"],
    position: { x: 902, y: 202 },
    metadata: { relativeChangePercent: -7.3, revenueImpactPerHourUsd: -12400, market: "US" },
  },
  {
    id: "node-incident",
    kind: "incident",
    title: "INC-2471 declared",
    subtitle: "SEV-2 · Checkout latency elevated",
    timestamp: "2026-07-14T09:24:00.000Z",
    severity: "critical",
    serviceId: "checkout-api",
    evidenceIds: ["ev-metric-checkout", "ev-trace-tax-7f91", "ev-commerce-conversion"],
    position: { x: 902, y: 82 },
    metadata: { incidentId: "INC-2471", commander: "Maya Chen" },
  },
  {
    id: "node-flag-disable",
    kind: "remediation",
    title: "instant-tax-v2 disabled",
    subtitle: "100% → 0% · human approved",
    timestamp: "2026-07-14T09:31:00.000Z",
    severity: "info",
    serviceId: "checkout-api",
    evidenceIds: ["ev-flag-instant-tax-v2", "ev-runbook-instant-tax-v2"],
    position: { x: 730, y: 326 },
    metadata: { flag: "instant-tax-v2", beforePercent: 100, afterPercent: 0, approver: "J. Lee", approvalRole: "Production Operator" },
  },
  {
    id: "node-recovery",
    kind: "remediation",
    title: "SLO returned to normal",
    subtitle: "p95 inside baseline for five minutes",
    timestamp: "2026-07-14T09:40:00.000Z",
    severity: "info",
    serviceId: "checkout-api",
    evidenceIds: ["ev-metric-checkout", "ev-flag-instant-tax-v2"],
    position: { x: 902, y: 326 },
    metadata: { latencyP95Ms: 680, verificationMinutes: 5, recoveryMinutes: 28 },
  },
];

export const causalEdges: readonly CausalEdge[] = [
  { id: "edge-change-deploy", source: "node-change-1842", target: "node-deploy-2180", relation: "deployed-as", label: "4 min later", confidence: 1, evidenceIds: ["ev-pr-1842", "ev-deploy-2180"] },
  { id: "edge-deploy-flag", source: "node-deploy-2180", target: "node-flag-rollout", relation: "introduced", label: "exposure doubled +6 min", confidence: 1, evidenceIds: ["ev-deploy-2180", "ev-flag-instant-tax-v2"] },
  { id: "edge-flag-checkout", source: "node-flag-rollout", target: "node-checkout", relation: "affected", label: "retry path at 100%", confidence: 0.98, evidenceIds: ["ev-flag-instant-tax-v2", "ev-trace-tax-7f91"] },
  { id: "edge-checkout-latency", source: "node-checkout", target: "node-latency", relation: "triggered", label: "critical path +1.16 s", confidence: 0.97, evidenceIds: ["ev-trace-tax-7f91", "ev-metric-checkout"] },
  { id: "edge-latency-alert", source: "node-latency", target: "node-alert", relation: "triggered", label: "SLO threshold", confidence: 1, evidenceIds: ["ev-metric-checkout"] },
  { id: "edge-checkout-trace", source: "node-checkout", target: "node-trace", relation: "confirmed-by", label: "pool-wait spans", confidence: 0.99, evidenceIds: ["ev-trace-tax-7f91"] },
  { id: "edge-trace-errors", source: "node-trace", target: "node-error-rate", relation: "triggered", label: "retry amplification", confidence: 0.95, evidenceIds: ["ev-trace-tax-7f91", "ev-metric-checkout"] },
  { id: "edge-errors-impact", source: "node-error-rate", target: "node-impact", relation: "correlated-with", label: "conversion window", confidence: 0.93, evidenceIds: ["ev-metric-checkout", "ev-commerce-conversion"] },
  { id: "edge-alert-incident", source: "node-alert", target: "node-incident", relation: "triggered", label: "SEV-2 declared", confidence: 1, evidenceIds: ["ev-metric-checkout"] },
  { id: "edge-impact-incident", source: "node-impact", target: "node-incident", relation: "correlated-with", label: "customer evidence", confidence: 0.96, evidenceIds: ["ev-commerce-conversion"] },
  { id: "edge-trace-incident", source: "node-trace", target: "node-incident", relation: "confirmed-by", label: "leading explanation", confidence: 0.98, evidenceIds: ["ev-trace-tax-7f91"] },
  { id: "edge-incident-flag-disable", source: "node-incident", target: "node-flag-disable", relation: "mitigated-by", label: "human approved", confidence: 1, evidenceIds: ["ev-runbook-instant-tax-v2", "ev-flag-instant-tax-v2"] },
  { id: "edge-flag-disable-recovery", source: "node-flag-disable", target: "node-recovery", relation: "resolved", label: "5 min inside baseline", confidence: 0.99, evidenceIds: ["ev-flag-instant-tax-v2", "ev-metric-checkout"] },
];

export const timelineEvents: readonly TimelineEvent[] = [
  { id: "tl-01", timestamp: "2026-07-14T09:08:00.000Z", kind: "change", title: "PR #1842 merged", description: "Outbound tax quote retries increased from one to three.", severity: "medium", serviceIds: ["checkout-api", "tax-adapter"], actor: "Maya Chen", evidenceIds: ["ev-pr-1842"] },
  { id: "tl-02", timestamp: "2026-07-14T09:12:00.000Z", kind: "deployment", title: "checkout-api@2.18.0 deployed", description: "Production rollout completed across all six instances.", severity: "info", serviceIds: ["checkout-api"], actor: "Release pipeline", evidenceIds: ["ev-deploy-2180"] },
  { id: "tl-03", timestamp: "2026-07-14T09:18:00.000Z", kind: "change", title: "instant-tax-v2 set to 100%", description: "Feature-flag exposure increased from 50% to 100%.", severity: "medium", serviceIds: ["checkout-api", "tax-adapter"], actor: "Release automation", evidenceIds: ["ev-flag-instant-tax-v2"] },
  { id: "tl-04", timestamp: "2026-07-14T09:21:20.000Z", kind: "metric", title: "Tax-adapter pool saturated", description: "Ninety-two percent of slow traces waited on connection acquisition.", severity: "high", serviceIds: ["checkout-api", "tax-adapter"], actor: "OpenTelemetry", evidenceIds: ["ev-trace-tax-7f91"] },
  { id: "tl-05", timestamp: "2026-07-14T09:21:30.000Z", kind: "alert", title: "Checkout p95 exceeded baseline", description: "Latency rose from 680 ms to 1.84 seconds while traffic remained stable.", severity: "critical", serviceIds: ["checkout-api"], actor: "SLO monitor", evidenceIds: ["ev-metric-checkout"] },
  { id: "tl-06", timestamp: "2026-07-14T09:22:00.000Z", kind: "alert", title: "Checkout errors and SLO burn increased", description: "Error rate reached 4.9% and short-window burn reached 8.4×.", severity: "critical", serviceIds: ["checkout-api", "tax-adapter"], actor: "SLO monitor", evidenceIds: ["ev-metric-checkout"] },
  { id: "tl-07", timestamp: "2026-07-14T09:23:00.000Z", kind: "metric", title: "Checkout conversion declined", description: "Conversion fell 7.3% relative, with an estimated $12.4k hourly impact.", severity: "critical", serviceIds: ["web-storefront", "checkout-api"], actor: "Meridian Commerce", evidenceIds: ["ev-commerce-conversion"] },
  { id: "tl-08", timestamp: "2026-07-14T09:24:00.000Z", kind: "incident", title: "INC-2471 declared SEV-2", description: "Maya Chen assumed command and Commerce Core checkout responders were paged.", severity: "critical", serviceIds: ["checkout-api", "tax-adapter", "web-storefront"], actor: "Maya Chen", evidenceIds: ["ev-metric-checkout", "ev-commerce-conversion"] },
  { id: "tl-09", timestamp: "2026-07-14T09:25:00.000Z", kind: "agent", title: "Threadline correlated seven signals", description: "The leading explanation joined PR #1842, version 2.18.0, flag exposure, pool waits, and customer impact.", severity: "info", serviceIds: ["checkout-api", "tax-adapter", "web-storefront"], actor: "Incident Investigator", evidenceIds: ["ev-pr-1842", "ev-deploy-2180", "ev-flag-instant-tax-v2", "ev-trace-tax-7f91", "ev-metric-checkout", "ev-commerce-conversion"] },
  { id: "tl-10", timestamp: "2026-07-14T09:27:00.000Z", kind: "decision", title: "Flag disable recommended", description: "The agent proposed setting instant-tax-v2 to 0% behind a human approval gate.", severity: "high", serviceIds: ["checkout-api", "tax-adapter"], actor: "Incident Investigator", evidenceIds: ["ev-runbook-instant-tax-v2"] },
  { id: "tl-11", timestamp: "2026-07-14T09:31:00.000Z", kind: "remediation", title: "Flag disable approved and executed", description: "Production Operator J. Lee approved instant-tax-v2 from 100% to 0%.", severity: "info", serviceIds: ["checkout-api", "tax-adapter"], actor: "J. Lee", evidenceIds: ["ev-flag-instant-tax-v2", "ev-runbook-instant-tax-v2"] },
  { id: "tl-12", timestamp: "2026-07-14T09:40:00.000Z", kind: "recovery", title: "Recovery verified", description: "Checkout p95 remained inside its 680 ms baseline band for five continuous minutes.", severity: "info", serviceIds: ["checkout-api", "tax-adapter", "web-storefront"], actor: "Maya Chen", evidenceIds: ["ev-metric-checkout"] },
];

const metricTimestamps = [
  "2026-07-14T09:04:00.000Z",
  "2026-07-14T09:08:00.000Z",
  "2026-07-14T09:12:00.000Z",
  "2026-07-14T09:16:00.000Z",
  "2026-07-14T09:18:00.000Z",
  "2026-07-14T09:21:00.000Z",
  "2026-07-14T09:23:00.000Z",
  "2026-07-14T09:27:00.000Z",
  "2026-07-14T09:31:00.000Z",
  "2026-07-14T09:35:00.000Z",
  "2026-07-14T09:40:00.000Z",
] as const;

function points(values: readonly number[]) {
  return metricTimestamps.map((timestamp, index) => ({
    timestamp,
    value: values[index] ?? 0,
  }));
}

export const metricSeries: readonly MetricSeries[] = [
  {
    id: "metric-checkout-p95",
    name: "Checkout request p95 latency",
    shortName: "p95 latency",
    serviceId: "checkout-api",
    unit: "ms",
    color: "#f43f5e",
    baseline: 680,
    threshold: 800,
    higherIsWorse: true,
    points: points([660, 690, 680, 720, 1100, 1840, 1760, 1480, 900, 700, 680]),
  },
  {
    id: "metric-checkout-errors",
    name: "Checkout request error rate",
    shortName: "Error rate",
    serviceId: "checkout-api",
    unit: "percent",
    color: "#fb923c",
    baseline: 0.7,
    threshold: 1,
    higherIsWorse: true,
    points: points([0.6, 0.7, 0.7, 0.8, 2.2, 4.9, 4.5, 3.1, 1.2, 0.8, 0.7]),
  },
  {
    id: "metric-checkout-conversion",
    name: "Checkout conversion",
    shortName: "Conversion",
    serviceId: "web-storefront",
    unit: "percent",
    color: "#8b5cf6",
    baseline: 68.4,
    threshold: 65,
    higherIsWorse: false,
    points: points([68.4, 68.7, 68.2, 68.5, 67.2, 63.5, 63.8, 65.1, 67.4, 68.1, 68.4]),
  },
  {
    id: "metric-checkout-volume",
    name: "Checkout request volume",
    shortName: "Throughput",
    serviceId: "checkout-api",
    unit: "rpm",
    color: "#22c55e",
    baseline: 1420,
    higherIsWorse: false,
    points: points([1410, 1420, 1416, 1428, 1408, 1392, 1398, 1412, 1424, 1418, 1422]),
  },
];

export const agentRuns: readonly AgentRun[] = [
  {
    id: "run-inc-2471",
    title: "Investigate INC-2471",
    mission: "incident-investigation",
    status: "completed",
    objective: "Find the first credible cause of checkout latency and propose a reversible mitigation.",
    trigger: "Checkout p95 SLO burn rate reached 8.4×",
    startedAt: "2026-07-14T09:22:00.000Z",
    finishedAt: "2026-07-14T09:40:00.000Z",
    progress: 1,
    confidence: 0.98,
    steps: [
      { id: "run-inc-1", title: "Collect signals", detail: "Joined PR, deployment, flag, trace, SLO, and commerce evidence by service and time.", status: "completed", startedAt: "2026-07-14T09:22:00.000Z", finishedAt: "2026-07-14T09:25:00.000Z" },
      { id: "run-inc-2", title: "Build causal thread", detail: "Ranked PR #1842 and instant-tax-v2 exposure as the leading explanation.", status: "completed", startedAt: "2026-07-14T09:23:00.000Z", finishedAt: "2026-07-14T09:25:00.000Z" },
      { id: "run-inc-3", title: "Check runbook", detail: "Matched the tax flag kill-switch and five-minute verification policy.", status: "completed", startedAt: "2026-07-14T09:25:00.000Z", finishedAt: "2026-07-14T09:27:00.000Z" },
      { id: "run-inc-4", title: "Request approval", detail: "Production Operator J. Lee approved disabling instant-tax-v2.", status: "completed", startedAt: "2026-07-14T09:27:00.000Z", finishedAt: "2026-07-14T09:31:00.000Z" },
      { id: "run-inc-5", title: "Verify recovery", detail: "Observed five continuous minutes inside the checkout latency baseline.", status: "completed", startedAt: "2026-07-14T09:31:00.000Z", finishedAt: "2026-07-14T09:40:00.000Z" },
    ],
    serviceIds: ["checkout-api", "tax-adapter", "web-storefront"],
    evidenceIds: ["ev-pr-1842", "ev-deploy-2180", "ev-flag-instant-tax-v2", "ev-trace-tax-7f91", "ev-metric-checkout", "ev-commerce-conversion", "ev-runbook-instant-tax-v2"],
    summary: "At 100% flag exposure, PR #1842 amplified outbound tax retries and saturated the tax-adapter pool. Human-approved flag disable restored p95.",
  },
  {
    id: "run-release-835",
    title: "Review payment SDK rollout",
    mission: "release-readiness",
    status: "awaiting-approval",
    objective: "Validate payment-token 6.4.2 for PCI and latency regressions before production.",
    trigger: "PR #835 entered the production queue",
    startedAt: "2026-07-14T10:11:00.000Z",
    finishedAt: null,
    progress: 0.82,
    confidence: 0.91,
    steps: [
      { id: "run-rel-1", title: "Inspect dependency diff", detail: "No transitive runtime packages added.", status: "completed", startedAt: "2026-07-14T10:11:00.000Z", finishedAt: "2026-07-14T10:14:00.000Z" },
      { id: "run-rel-2", title: "Compare canary traces", detail: "p95 authorization latency changed by +0.7%.", status: "completed", startedAt: "2026-07-14T10:14:00.000Z", finishedAt: "2026-07-14T10:23:00.000Z" },
      { id: "run-rel-3", title: "Check PCI controls", detail: "Attestation and token redaction checks passed.", status: "completed", startedAt: "2026-07-14T10:23:00.000Z", finishedAt: "2026-07-14T10:29:00.000Z" },
      { id: "run-rel-4", title: "Approve production rollout", detail: "Money Movement owner approval is required.", status: "blocked", startedAt: "2026-07-14T10:29:00.000Z", finishedAt: null },
    ],
    serviceIds: ["payments", "checkout-api"],
    evidenceIds: [],
    summary: "Automated checks passed. Production rollout is held at the human approval boundary.",
  },
  {
    id: "run-slo-checkout",
    title: "Guard checkout error budget",
    mission: "slo-guard",
    status: "running",
    objective: "Watch multi-window burn rate after INC-2471 and halt risky checkout changes.",
    trigger: "INC-2471 moved to resolved",
    startedAt: "2026-07-14T09:40:00.000Z",
    finishedAt: null,
    progress: 0.68,
    confidence: 0.96,
    steps: [
      { id: "run-slo-1", title: "Recalculate budget", detail: "Thirty-day budget remaining is 42.6%.", status: "completed", startedAt: "2026-07-14T09:40:00.000Z", finishedAt: "2026-07-14T09:41:00.000Z" },
      { id: "run-slo-2", title: "Watch recovery window", detail: "Two-hour burn rate remains below 1×.", status: "running", startedAt: "2026-07-14T09:41:00.000Z", finishedAt: null },
      { id: "run-slo-3", title: "Release deployment hold", detail: "Requires 120 stable minutes.", status: "pending", startedAt: null, finishedAt: null },
    ],
    serviceIds: ["checkout-api", "tax-adapter", "web-storefront"],
    evidenceIds: ["ev-metric-checkout", "ev-flag-instant-tax-v2"],
    summary: "Recovery is stable; checkout deployments remain constrained until 11:40 UTC.",
  },
  {
    id: "run-review-826",
    title: "Review session key rotation",
    mission: "change-review",
    status: "completed",
    objective: "Assess authentication blast radius and test coverage for PR #826.",
    trigger: "Risk policy flagged a large Tier-0 authentication diff",
    startedAt: "2026-07-14T04:11:00.000Z",
    finishedAt: "2026-07-14T04:24:00.000Z",
    progress: 1,
    confidence: 0.89,
    steps: [
      { id: "run-rev-1", title: "Map callers", detail: "Found 17 session-token consumers across six repositories.", status: "completed", startedAt: "2026-07-14T04:11:00.000Z", finishedAt: "2026-07-14T04:16:00.000Z" },
      { id: "run-rev-2", title: "Inspect failure modes", detail: "Concurrent rotation lacks a stale-key integration test.", status: "completed", startedAt: "2026-07-14T04:16:00.000Z", finishedAt: "2026-07-14T04:21:00.000Z" },
      { id: "run-rev-3", title: "Publish review", detail: "Blocked rollout pending dual-key overlap coverage.", status: "completed", startedAt: "2026-07-14T04:21:00.000Z", finishedAt: "2026-07-14T04:24:00.000Z" },
    ],
    serviceIds: ["identity", "edge-gateway"],
    evidenceIds: [],
    summary: "Rollout blocked: add a concurrent dual-key overlap test and a rollback drill.",
  },
  {
    id: "run-postmortem-2471",
    title: "Draft INC-2471 review",
    mission: "postmortem",
    status: "running",
    objective: "Produce an evidence-linked incident review with owners and measurable follow-ups.",
    trigger: "INC-2471 resolved",
    startedAt: "2026-07-14T09:42:00.000Z",
    finishedAt: null,
    progress: 0.56,
    confidence: 0.94,
    steps: [
      { id: "run-pm-1", title: "Assemble timeline", detail: "Twelve events normalized to UTC.", status: "completed", startedAt: "2026-07-14T09:42:00.000Z", finishedAt: "2026-07-14T09:45:00.000Z" },
      { id: "run-pm-2", title: "Verify causal claims", detail: "Every causal claim links to primary evidence.", status: "completed", startedAt: "2026-07-14T09:45:00.000Z", finishedAt: "2026-07-14T09:54:00.000Z" },
      { id: "run-pm-3", title: "Draft actions", detail: "Proposing retry-budget load tests and graduated flag-rollout gates.", status: "running", startedAt: "2026-07-14T09:54:00.000Z", finishedAt: null },
      { id: "run-pm-4", title: "Request owner sign-off", detail: "Checkout Reliability and Core Platform sign-off pending.", status: "pending", startedAt: null, finishedAt: null },
    ],
    serviceIds: ["checkout-api", "tax-adapter", "web-storefront"],
    evidenceIds: ["ev-pr-1842", "ev-deploy-2180", "ev-flag-instant-tax-v2", "ev-trace-tax-7f91", "ev-metric-checkout", "ev-commerce-conversion", "ev-runbook-instant-tax-v2"],
    summary: "Timeline and root cause are verified; corrective-action ownership is in progress.",
  },
];

export const reportMetrics: ReportMetrics = {
  window: {
    label: "Last 30 days",
    from: "2026-06-15T00:00:00.000Z",
    to: "2026-07-14T10:42:00.000Z",
  },
  generatedAt: DEMO_NOW,
  dora: [
    {
      id: "deployment-frequency",
      label: "Deployment frequency",
      value: 6.8,
      displayValue: "6.8 / day",
      unit: "per-day",
      trend: "up",
      delta: 0.9,
      deltaLabel: "+0.9 vs prior period",
      status: "excellent",
    },
    {
      id: "change-lead-time",
      label: "Change lead time",
      value: 38,
      displayValue: "38 min",
      unit: "minutes",
      trend: "down",
      delta: -12,
      deltaLabel: "12 min faster",
      status: "excellent",
    },
    {
      id: "failed-deployment-recovery-time",
      label: "Failed deployment recovery",
      value: 28,
      displayValue: "28 min",
      unit: "minutes",
      trend: "down",
      delta: -12,
      deltaLabel: "12 min faster",
      status: "good",
    },
    {
      id: "change-fail-rate",
      label: "Change fail rate",
      value: 6.4,
      displayValue: "6.4%",
      unit: "percent",
      trend: "up",
      delta: 1.2,
      deltaLabel: "+1.2 pp vs prior period",
      status: "needs-attention",
    },
    {
      id: "deployment-rework-rate",
      label: "Deployment rework rate",
      value: 3.1,
      displayValue: "3.1%",
      unit: "percent",
      trend: "down",
      delta: -0.8,
      deltaLabel: "0.8 pp lower",
      status: "good",
    },
  ],
  slos: [
    {
      id: "slo-checkout-availability",
      name: "Checkout availability",
      serviceId: "checkout-api",
      target: 99.95,
      current: 99.921,
      errorBudgetRemaining: 42.6,
      burnRate: 0.84,
      windowDays: 30,
      status: "warning",
    },
    {
      id: "slo-checkout-latency",
      name: "Checkout p95 under 800 ms",
      serviceId: "checkout-api",
      target: 99.9,
      current: 99.874,
      errorBudgetRemaining: 36.8,
      burnRate: 0.92,
      windowDays: 30,
      status: "warning",
    },
    {
      id: "slo-payments-availability",
      name: "Payment authorization availability",
      serviceId: "payments",
      target: 99.99,
      current: 99.994,
      errorBudgetRemaining: 81.4,
      burnRate: 0.26,
      windowDays: 30,
      status: "healthy",
    },
    {
      id: "slo-storefront-availability",
      name: "Storefront availability",
      serviceId: "web-storefront",
      target: 99.95,
      current: 99.982,
      errorBudgetRemaining: 72.1,
      burnRate: 0.41,
      windowDays: 30,
      status: "healthy",
    },
  ],
  incident: {
    count: 3,
    customerImpactMinutes: 47,
    medianAcknowledgeMinutes: 3.2,
    medianResolveMinutes: 28,
  },
};

export const attentionItems: readonly AttentionItem[] = [
  {
    id: "attention-inc-2471",
    title: "INC-2471 follow-ups need owners",
    description: "Two corrective actions in the draft review are still unassigned.",
    severity: "high",
    category: "incident",
    serviceId: "checkout-api",
    href: "/incidents/inc-2471",
    dueAt: "2026-07-15T09:00:00.000Z",
  },
  {
    id: "attention-payment-sdk",
    title: "Payment SDK rollout awaits approval",
    description: "Automated checks passed; Money Movement sign-off is required.",
    severity: "medium",
    category: "agent",
    serviceId: "payments",
    href: "/agents/run-release-835",
    dueAt: "2026-07-14T12:00:00.000Z",
  },
  {
    id: "attention-checkout-slo",
    title: "Checkout budget below 50%",
    description: "Availability error budget has 42.6% remaining for the 30-day window.",
    severity: "medium",
    category: "slo",
    serviceId: "checkout-api",
    href: "/reports#slo-checkout-availability",
    dueAt: null,
  },
  {
    id: "attention-session-key",
    title: "Session key rotation blocked",
    description: "PR #826 needs dual-key overlap coverage before deployment.",
    severity: "high",
    category: "security",
    serviceId: "identity",
    href: "/changes/chg-826",
    dueAt: "2026-07-16T08:00:00.000Z",
  },
];

export const pulseMetrics: readonly PulseMetric[] = [
  {
    id: "pulse-health",
    label: "Service health",
    value: 6,
    displayValue: "6 / 8 healthy",
    detail: "Checkout is critical; Tax adapter is degraded",
    trend: "down",
    tone: "warning",
  },
  {
    id: "pulse-incidents",
    label: "Active incidents",
    value: 0,
    displayValue: "0 active",
    detail: "INC-2471 resolved 62 minutes ago",
    trend: "down",
    tone: "positive",
  },
  {
    id: "pulse-deployments",
    label: "Deployments today",
    value: 14,
    displayValue: "14 shipped",
    detail: "One flag disable · one canary active",
    trend: "up",
    tone: "neutral",
  },
  {
    id: "pulse-agents",
    label: "Agent runs",
    value: 2,
    displayValue: "2 running",
    detail: "One approval required",
    trend: "flat",
    tone: "neutral",
  },
  {
    id: "pulse-budget",
    label: "Lowest error budget",
    value: 36.8,
    displayValue: "36.8%",
    detail: "Checkout latency · 30-day window",
    trend: "down",
    tone: "warning",
  },
];
